import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutShell from "@/components/LayoutShell";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  // Title template — page-level `metadata.title` strings get formatted as
  // "[page] · Pascal" instead of replacing the whole title.
  title: {
    default: "Pascal · AI Support",
    template: "%s · Pascal",
  },
  description:
    "Pascal — Tonder's AI Support agent. Live merchant channels, analytics, knowledge base, and team operations console.",
  applicationName: "Pascal",
  // Next.js auto-injects <link rel="manifest"> when app/manifest.ts exists,
  // but declaring it here is explicit and survives the metadata API.
  manifest: "/manifest.webmanifest",
  // iOS / macOS Sonoma "Add to Dock" specific. The PNG fallbacks come from
  // app/apple-icon.png (Next.js convention) — these explicit entries let us
  // be precise about sizes if we ever ship multiple.
  appleWebApp: {
    capable: true,
    title: "Pascal",
    // black-translucent renders our page chrome under the iOS status bar,
    // giving a more native feel. Pair with viewport-fit=cover (below).
    statusBarStyle: "black-translucent",
  },
  // Hint to search engines + iOS Smart App Banner / Open Graph fallbacks.
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  // Theme color is what the system uses for the title bar / status bar in
  // installed PWA contexts (macOS Sonoma "Add to Dock", iOS standalone mode,
  // Android Chrome). Different values for light vs. dark UI feel native.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0d1227" },
  ],
  // viewport-fit=cover lets the page extend behind iPhone notches / Dynamic
  // Island; we use this together with black-translucent status bar style.
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // iOS 16.4+ / Android 108+ — tell the browser to RESIZE the viewport
  // when the soft keyboard appears, instead of overlaying it on top of
  // a same-sized viewport (the default `overlays-content`). With this:
  // 100dvh actually shrinks while the keyboard is open, the chat layout
  // reflows naturally, and Safari stops document-scrolling to keep the
  // focused input visible (which was breaking the /chat layout). The
  // v4 visualViewport hook stays as a fallback for older iOS.
  interactiveWidget: "resizes-content",
};

/**
 * iPhone PWA splash screens — Safari shows a brief white flash when an
 * installed PWA boots unless we declare a splash that matches the device.
 * The `media` query tells Safari which PNG to use for each device's exact
 * logical viewport + device-pixel-ratio. Coverage: iPhone 12 → 16 family
 * (standard, Pro, Plus, Pro Max). Generated by
 * scripts/generate-splash-screens.js — re-run after editing the source logo.
 */
const SPLASHES: { href: string; media: string }[] = [
  {
    // iPhone 16 Pro Max — 440×956 @3x
    href: "/splash/iphone-16-promax.png",
    media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  {
    // iPhone 16 Pro — 402×874 @3x
    href: "/splash/iphone-16-pro.png",
    media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  {
    // iPhone 14/15 Pro Max, iPhone 15/16 Plus — 430×932 @3x
    href: "/splash/iphone-15-promax.png",
    media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  {
    // iPhone 14/15/16 Pro, iPhone 15/16 — 393×852 @3x
    href: "/splash/iphone-15-pro.png",
    media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  {
    // iPhone 12/13/14 Pro Max, iPhone 14 Plus — 428×926 @3x
    href: "/splash/iphone-14-plus.png",
    media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
  {
    // iPhone 12/13/14 standard, iPhone 12/13 Pro — 390×844 @3x
    href: "/splash/iphone-12.png",
    media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        {SPLASHES.map((s) => (
          <link
            key={s.href}
            rel="apple-touch-startup-image"
            href={s.href}
            media={s.media}
          />
        ))}
      </head>
      <body className="bg-gray-50 text-gray-900 min-h-screen flex">
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
